### PR TITLE
Filter citeb-by events from crossref agent

### PR DESCRIPTION
**Pull request by kjgarza**
Crossref started making its cited-by service citations available in eventdata since october https://docs.google.com/document/d/1uz9q2IKS7_kWebP19X2v7daBUr3duLKXmN6cWcMRkaY/edit#bookmark=id.r0biw9yctzj0 , however they did it under the same source-id as other crossref events. Theses event do not include datacite dois and thus might not be essential for Datacite at the moment.

Crossref told us how to filter them in Feb

https://www.eventdata.crossref.org/guide/service/query-api/

## Purpose

closes: _Add github issue that originated this PR_

## Learning

See total-results 

https://api.eventdata.crossref.org/v1/events?source=crossref&from-occurred-date=2021-11-01&scholix=true 

and 

https://api.eventdata.crossref.org/v1/events?source=crossref&from-occurred-date=2021-11-01 (no filter)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines): 

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Review by digitaldogsbody — APPROVED** [review]
I am not 100% up to speed with what Scholix is and how it fits our workflow. Are _all_ Datacite DOIs also in the Scholix index (and thus visible with this query parameter)?

**Comment by kjgarza** [comment]
See total-results https://api.eventdata.crossref.org/v1/events?source=crossref&from-occurred-date=2021-11-01&scholix=true and https://api.eventdata.crossref.org/v1/events?source=crossref&from-occurred-date=2021-11-01 (no filter)

**Comment by kjgarza** [comment]
It would be useful @digitaldogsbody @richardhallett 

- to check that DOIs in the events at least have datacite DOI.
- and format is the same

**Comment by richardhallett** [comment]
This looks okay to me, I can see DataCite dois referenced in the returned data, and the API format isnt any different.
I will go ahead and merge this as we need to filter out CrossRef to Crossref Events.

**Review by richardhallett — APPROVED** [review]

**Pull request merged**
